package StuPackage;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class EditAssessmentFrame extends javax.swing.JFrame {

    private String stuID;

    /**
     * Creates new form EditAssessmentFrame
     */
    public EditAssessmentFrame(String StuID) {
        //Pass the Student ID to class object(stuID)
        stuID = StuID;

        //GUI setting
        initComponents();
        getContentPane().setBackground(new Color(204, 204, 255));

        //Search the selected student data
        for (int i = 0; i < StuData_IO.StuData.size(); i++) {
            if (StuData_IO.StuData.get(i).id.equals(StuID)) {
                lbSelectedName.setText(StuData_IO.StuData.get(i).name);
                lbSelectedID.setText(StuData_IO.StuData.get(i).id);
                break;
            }
        }

        cboAssesment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"-", "Intern", "Invt Report", "CP1", "CP2", "RMCP", "FYP"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStuName = new javax.swing.JLabel();
        lbSelectedName = new javax.swing.JLabel();
        lbStuID = new javax.swing.JLabel();
        lbSelectedID = new javax.swing.JLabel();
        cboAssesment = new javax.swing.JComboBox<>();
        lbAssesment = new javax.swing.JLabel();
        btbSubmit = new javax.swing.JButton();
        btbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lbStuName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbStuName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStuName.setText("Student Name: ");

        lbSelectedName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbSelectedName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSelectedName.setText(" ");

        lbStuID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbStuID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbStuID.setText("Student ID: ");

        lbSelectedID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbSelectedID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSelectedID.setText(" ");

        cboAssesment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbAssesment.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbAssesment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAssesment.setText("Assessment: ");

        btbSubmit.setText("Submit");
        btbSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSubmitActionPerformed(evt);
            }
        });

        btbCancel.setText("Cancel");
        btbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btbSubmit)
                        .addGap(51, 51, 51)
                        .addComponent(btbCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbAssesment)
                            .addComponent(lbStuName)
                            .addComponent(lbStuID))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSelectedID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbSelectedName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboAssesment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStuName)
                    .addComponent(lbSelectedName))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStuID)
                    .addComponent(lbSelectedID))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAssesment)
                    .addComponent(cboAssesment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbSubmit)
                    .addComponent(btbCancel))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelActionPerformed
        //Return back to the student list page
        this.setVisible(false);
        StuAssessmentList NwFrame = new StuAssessmentList();
        NwFrame.setVisible(true);
    }//GEN-LAST:event_btbCancelActionPerformed

    private void btbSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSubmitActionPerformed
        //Search the selected student location and
        int Index = StuData_IO.checkStu(stuID);

        //Get all the selected student data
        String Name = StuData_IO.StuData.get(Index).name;
        int Age = StuData_IO.StuData.get(Index).age;
        String Intake = StuData_IO.StuData.get(Index).intake;
        String Assessment = (String) cboAssesment.getSelectedItem();
        String Supervisor = StuData_IO.StuData.get(Index).supervisor;
        String SecondMaker = StuData_IO.StuData.get(Index).secondMaker;

        //Update the edited data into ArrayList
        Student Edited_Student = new Student(Name, Age, stuID, Intake, Assessment, Supervisor, SecondMaker);
        StuData_IO.edit(Index, Edited_Student);

        //Return back to the student list page
        this.setVisible(false);
        StuAssessmentList NwFrame = new StuAssessmentList();
        NwFrame.setVisible(true);
    }//GEN-LAST:event_btbSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAssessmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAssessmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAssessmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAssessmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCancel;
    private javax.swing.JButton btbSubmit;
    private javax.swing.JComboBox<String> cboAssesment;
    private javax.swing.JLabel lbAssesment;
    private javax.swing.JLabel lbSelectedID;
    private javax.swing.JLabel lbSelectedName;
    private javax.swing.JLabel lbStuID;
    private javax.swing.JLabel lbStuName;
    // End of variables declaration//GEN-END:variables
}
