package StuPackage;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class PanelDashboard extends javax.swing.JPanel {
    private String username; // Declare as an instance variable
    private String password;
    
    public PanelDashboard(String username, String password) {
        initComponents();
        this.username = username; // Assign the parameter value to the instance variable
        this.password = password; 
        
        readStudentDetailsFromFile("StuData.txt");
    }

private void readStudentDetailsFromFile(String fileName) {
    try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts[0].trim().equals(username)) { 
                StuID.setText(parts[0].trim());
                StuName.setText(parts[2].trim());
                StuAge.setText(parts[3].trim());
                StuIntake.setText(parts[4].trim());
                StuAssessment.setText(parts[5].trim());
                LecSupName.setText(parts[6].trim());
                return; // Exit the loop once the user is found
            }
        }
        // If the loop completes without finding the user
        System.err.println("User not found in the file.");
    } catch (IOException e) {
        System.err.println("Error reading the file: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        StuName = new javax.swing.JLabel();
        StuID = new javax.swing.JLabel();
        StuIntake = new javax.swing.JLabel();
        StuAge = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LecSupName = new javax.swing.JLabel();
        StuAssessment = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(935, 530));

        jPanel1.setPreferredSize(new java.awt.Dimension(935, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StuName.setBackground(new java.awt.Color(255, 255, 255));
        StuName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        StuName.setForeground(new java.awt.Color(255, 255, 255));
        StuName.setText("Student Name");
        jPanel2.add(StuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        StuID.setBackground(new java.awt.Color(255, 255, 255));
        StuID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StuID.setForeground(new java.awt.Color(255, 255, 255));
        StuID.setText("Student ID");
        jPanel2.add(StuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        StuIntake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StuIntake.setForeground(new java.awt.Color(255, 255, 255));
        StuIntake.setText("Intake");
        jPanel2.add(StuIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, -1));

        StuAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        StuAge.setForeground(new java.awt.Color(255, 255, 255));
        StuAge.setText("Age");
        jPanel2.add(StuAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Supervisor/Lecturer Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Student Age");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo(White).png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Academic Guidance Hub ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 390, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 100));

        LecSupName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LecSupName.setForeground(new java.awt.Color(255, 255, 255));
        LecSupName.setText("TEXT");
        jPanel2.add(LecSupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 150, -1));

        StuAssessment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StuAssessment.setForeground(new java.awt.Color(255, 255, 255));
        StuAssessment.setText("TEXT");
        jPanel2.add(StuAssessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 130, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Assessment");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Student ID");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Student Intake");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 670, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LecSupName;
    private javax.swing.JLabel StuAge;
    private javax.swing.JLabel StuAssessment;
    private javax.swing.JLabel StuID;
    private javax.swing.JLabel StuIntake;
    private javax.swing.JLabel StuName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
