package AdminPackage;

import Java_Assignment.LoginPage;
import ProjManagerPackage.AssignSupvElem.LectData_IO;
import StuPackage.StuData_IO;
import Lecturer_Package.lect_Panal;
import java.awt.Color;


public class Admin_MainFrame extends javax.swing.JFrame {

    // Color for side nav bar tab
    private Color navDefaultColor = new Color(255, 148, 148);
    private Color navSelectedColor = new Color(252, 188, 188);
    
    
    public Admin_MainFrame() {
        initComponents();
        getContentPane().setBackground(new Color(255, 245, 228));
        
        
        /* Set the tab panel */
        //Intake Management Panel Section
        Admin_IntakeMgmtPane Tab0 = new Admin_IntakeMgmtPane(this);
        TabPanel.addTab("Tab0", Tab0);            

//        Student Management Panel Section
        Admin_StudentManagement Tab1 = new Admin_StudentManagement(this);
        TabPanel.addTab("Tab1", Tab1);

        //Lecturer Management Panel Section
        lect_Panal lect_panal = new lect_Panal(this);
        TabPanel.addTab("Tab2", lect_panal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideNavBar = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        IntakeMgmtPane = new javax.swing.JPanel();
        navIntakeMgmt = new javax.swing.JLabel();
        StuMgmtPane = new javax.swing.JPanel();
        navStuMgmt = new javax.swing.JLabel();
        LectMgmtPane = new javax.swing.JPanel();
        navAssignAdvisors = new javax.swing.JLabel();
        topNavBar = new javax.swing.JPanel();
        PanelTitle = new javax.swing.JLabel();
        AccName = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        CoverTabPane = new javax.swing.JPanel();
        TabPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 246, 227));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideNavBar.setBackground(new java.awt.Color(255, 148, 148));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo(White).png"))); // NOI18N

        IntakeMgmtPane.setBackground(new java.awt.Color(252, 188, 188));

        navIntakeMgmt.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        navIntakeMgmt.setForeground(new java.awt.Color(255, 255, 255));
        navIntakeMgmt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navIntakeMgmt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AdminIntake.png"))); // NOI18N
        navIntakeMgmt.setText("Intake Management");
        navIntakeMgmt.setIconTextGap(15);
        navIntakeMgmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navIntakeMgmtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout IntakeMgmtPaneLayout = new javax.swing.GroupLayout(IntakeMgmtPane);
        IntakeMgmtPane.setLayout(IntakeMgmtPaneLayout);
        IntakeMgmtPaneLayout.setHorizontalGroup(
            IntakeMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntakeMgmtPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(navIntakeMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        IntakeMgmtPaneLayout.setVerticalGroup(
            IntakeMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntakeMgmtPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(navIntakeMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        StuMgmtPane.setBackground(new java.awt.Color(255, 148, 148));

        navStuMgmt.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        navStuMgmt.setForeground(new java.awt.Color(255, 255, 255));
        navStuMgmt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navStuMgmt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ProjMngStuAsse.png"))); // NOI18N
        navStuMgmt.setText("Student Management");
        navStuMgmt.setDoubleBuffered(true);
        navStuMgmt.setIconTextGap(15);
        navStuMgmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navStuMgmtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout StuMgmtPaneLayout = new javax.swing.GroupLayout(StuMgmtPane);
        StuMgmtPane.setLayout(StuMgmtPaneLayout);
        StuMgmtPaneLayout.setHorizontalGroup(
            StuMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StuMgmtPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(navStuMgmt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StuMgmtPaneLayout.setVerticalGroup(
            StuMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StuMgmtPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(navStuMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        LectMgmtPane.setBackground(new java.awt.Color(255, 148, 148));

        navAssignAdvisors.setBackground(new java.awt.Color(255, 148, 148));
        navAssignAdvisors.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        navAssignAdvisors.setForeground(new java.awt.Color(255, 255, 255));
        navAssignAdvisors.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navAssignAdvisors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ProjMngSupervisor.png"))); // NOI18N
        navAssignAdvisors.setText("Lecturer Management");
        navAssignAdvisors.setIconTextGap(15);
        navAssignAdvisors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAssignAdvisorsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LectMgmtPaneLayout = new javax.swing.GroupLayout(LectMgmtPane);
        LectMgmtPane.setLayout(LectMgmtPaneLayout);
        LectMgmtPaneLayout.setHorizontalGroup(
            LectMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LectMgmtPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(navAssignAdvisors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LectMgmtPaneLayout.setVerticalGroup(
            LectMgmtPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LectMgmtPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(navAssignAdvisors, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout sideNavBarLayout = new javax.swing.GroupLayout(sideNavBar);
        sideNavBar.setLayout(sideNavBarLayout);
        sideNavBarLayout.setHorizontalGroup(
            sideNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideNavBarLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addComponent(IntakeMgmtPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StuMgmtPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LectMgmtPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideNavBarLayout.setVerticalGroup(
            sideNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideNavBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(IntakeMgmtPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(StuMgmtPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(LectMgmtPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        getContentPane().add(sideNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        topNavBar.setBackground(new java.awt.Color(252, 188, 188));

        PanelTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        PanelTitle.setForeground(new java.awt.Color(255, 255, 255));
        PanelTitle.setText("Intake Management");

        AccName.setFont(new java.awt.Font("Dubai Medium", 0, 28)); // NOI18N
        AccName.setForeground(new java.awt.Color(255, 255, 255));
        AccName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AccName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ProjMngUser.png"))); // NOI18N
        AccName.setText("Admin");
        AccName.setIconTextGap(10);

        lblLogout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topNavBarLayout = new javax.swing.GroupLayout(topNavBar);
        topNavBar.setLayout(topNavBarLayout);
        topNavBarLayout.setHorizontalGroup(
            topNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topNavBarLayout.createSequentialGroup()
                .addGroup(topNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(topNavBarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(PanelTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                        .addComponent(AccName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topNavBarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogout)))
                .addGap(20, 20, 20))
        );
        topNavBarLayout.setVerticalGroup(
            topNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topNavBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogout)
                .addGap(3, 3, 3)
                .addGroup(topNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(topNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 975, -1));

        CoverTabPane.setBackground(new java.awt.Color(255, 245, 228));

        javax.swing.GroupLayout CoverTabPaneLayout = new javax.swing.GroupLayout(CoverTabPane);
        CoverTabPane.setLayout(CoverTabPaneLayout);
        CoverTabPaneLayout.setHorizontalGroup(
            CoverTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        CoverTabPaneLayout.setVerticalGroup(
            CoverTabPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(CoverTabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 940, 30));

        TabPanel.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        getContentPane().add(TabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 94, 920, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void navIntakeMgmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navIntakeMgmtMouseClicked
        IntakeMgmtPane.setBackground(navSelectedColor);
        StuMgmtPane.setBackground(navDefaultColor);
        LectMgmtPane.setBackground(navDefaultColor);
        
        PanelTitle.setText("Intake Management");
        changedTab(0);
    }//GEN-LAST:event_navIntakeMgmtMouseClicked

    private void navStuMgmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navStuMgmtMouseClicked
        IntakeMgmtPane.setBackground(navDefaultColor);
        StuMgmtPane.setBackground(navSelectedColor);
        LectMgmtPane.setBackground(navDefaultColor);
        
        PanelTitle.setText("Student Management");
        changedTab(1);
    }//GEN-LAST:event_navStuMgmtMouseClicked

    private void navAssignAdvisorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAssignAdvisorsMouseClicked
        IntakeMgmtPane.setBackground(navDefaultColor);
        StuMgmtPane.setBackground(navDefaultColor);
        LectMgmtPane.setBackground(navSelectedColor);
        
        PanelTitle.setText("Lecturer Management");
        changedTab(2);
    }//GEN-LAST:event_navAssignAdvisorsMouseClicked

    /* Logout Button */
    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked

        // Redirect to login page or close the current window
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        this.dispose(); // Close the current window
    }//GEN-LAST:event_lblLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    
   //Change panel tab method
    public static void changedTab(int TabIndex){
        TabPanel.setSelectedIndex(TabIndex);
    }

    //Create new temperory panel tab - AssignAdvsTab_IntakeList
    public static void updateIntakeMgmtPane(Admin_MainFrame mainFrame){
        Admin_IntakeMgmtPane lastTab = new Admin_IntakeMgmtPane(mainFrame);
        TabPanel.addTab("IntakeListtab", lastTab);
    }
    
    public static void Admin_StudentManagement(Admin_MainFrame mainFrame){
        Admin_StudentManagement lastTab = new Admin_StudentManagement(mainFrame);
        TabPanel.addTab("IntakeListtab", lastTab);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IntakeRecord.readFrTxt();
                StuData_IO.readFrTxt();
                LectData_IO.readFrTxt();
                new Admin_MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccName;
    private javax.swing.JPanel CoverTabPane;
    public javax.swing.JPanel IntakeMgmtPane;
    public javax.swing.JPanel LectMgmtPane;
    public javax.swing.JLabel PanelTitle;
    public javax.swing.JPanel StuMgmtPane;
    public static javax.swing.JTabbedPane TabPanel;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel navAssignAdvisors;
    private javax.swing.JLabel navIntakeMgmt;
    private javax.swing.JLabel navStuMgmt;
    private javax.swing.JPanel sideNavBar;
    private javax.swing.JPanel topNavBar;
    // End of variables declaration//GEN-END:variables
}
