package ProjManagerPackage;

import ProjManagerPackage.StuAssesElem.IntakeBasedMethod;
import StuPackage.StuData_IO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class AccMgmtFrame_EditStu extends javax.swing.JFrame {

    private String SelectedStuID;
    private String SelectedIntake;
    
    public AccMgmtFrame_EditStu(String selectedStuID, String selectedIntake) {
        SelectedStuID = selectedStuID;
        SelectedIntake = selectedIntake;
        
        //GUI Setting
        initComponents();
        getContentPane().setBackground(new Color(122, 162, 227));
        
        //Set the option of current available intake
        ArrayList<String> intakeArray = IntakeBasedMethod.getIntake();
        String[] intakeList = intakeArray.toArray(new String[0]);
        cboStuIntake.setModel(new javax.swing.DefaultComboBoxModel<>(intakeList));
        
        //Search the selected student data
        for (int i = 0; i < StuData_IO.StuData.size(); i++) {
            if (StuData_IO.StuData.get(i).id.equals(selectedStuID)) {
                TFStuName.setText(StuData_IO.StuData.get(i).name);
                TFStuID.setText(StuData_IO.StuData.get(i).id);
                TFStuAge.setText(String.valueOf(StuData_IO.StuData.get(i).age));
                cboStuIntake.setSelectedItem(StuData_IO.StuData.get(i).intake);
                break;
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStuName = new javax.swing.JLabel();
        lblStuID = new javax.swing.JLabel();
        btbSubmit = new javax.swing.JButton();
        btbCancel = new javax.swing.JButton();
        TFStuName = new javax.swing.JTextField();
        TFStuID = new javax.swing.JTextField();
        lblLectID1 = new javax.swing.JLabel();
        TFStuAge = new javax.swing.JTextField();
        lblStuAge = new javax.swing.JLabel();
        cboStuIntake = new javax.swing.JComboBox<>();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        iconTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblStuName.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblStuName.setForeground(new java.awt.Color(0, 0, 0));
        lblStuName.setText("Student Name:");

        lblStuID.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblStuID.setForeground(new java.awt.Color(0, 0, 0));
        lblStuID.setText("Student ID:");

        btbSubmit.setBackground(new java.awt.Color(122, 162, 227));
        btbSubmit.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        btbSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btbSubmit.setText("Submit");
        btbSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSubmitActionPerformed(evt);
            }
        });

        btbCancel.setBackground(new java.awt.Color(122, 162, 227));
        btbCancel.setFont(new java.awt.Font("Dubai Medium", 1, 15)); // NOI18N
        btbCancel.setForeground(new java.awt.Color(255, 255, 255));
        btbCancel.setText("Cancel");
        btbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelActionPerformed(evt);
            }
        });

        TFStuName.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N

        TFStuID.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N

        lblLectID1.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblLectID1.setForeground(new java.awt.Color(0, 0, 0));
        lblLectID1.setText("Age:");

        TFStuAge.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N

        lblStuAge.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblStuAge.setForeground(new java.awt.Color(0, 0, 0));
        lblStuAge.setText("Intake:");

        cboStuIntake.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btbSubmit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStuName)
                            .addComponent(lblStuID)
                            .addComponent(lblStuAge)
                            .addComponent(lblLectID1))
                        .addGap(17, 17, 17)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btbCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFStuAge)
                            .addComponent(TFStuID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFStuName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboStuIntake, 0, 147, Short.MAX_VALUE))))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStuName)
                    .addComponent(TFStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStuID)
                    .addComponent(TFStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLectID1)
                    .addComponent(TFStuAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStuAge)
                    .addComponent(cboStuIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbCancel)
                    .addComponent(btbSubmit))
                .addGap(50, 50, 50))
        );

        lblTitle2.setFont(new java.awt.Font("Dubai Medium", 1, 38)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("Account");

        lblTitle1.setFont(new java.awt.Font("Dubai Medium", 1, 38)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Edit Student");

        iconTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/StuIcon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblTitle2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(iconTitle)))
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconTitle)
                .addGap(0, 0, 0)
                .addComponent(lblTitle1)
                .addGap(0, 0, 0)
                .addComponent(lblTitle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSubmitActionPerformed
        
        try{
            //Search the selected student location
            int stuIndex = StuData_IO.checkStu(SelectedStuID);

            //Get all the edited input data
            String editedName = TFStuName.getText();
            String editedID = TFStuID.getText();
            int editedAge = Integer.parseInt(TFStuAge.getText());
            String editedIntake = (String) cboStuIntake.getSelectedItem();


            //Update the edited student data into ArrayList
            if (!editedIntake.equals(SelectedIntake)) {
                ProjManager.editStuAcc_differentIntake(stuIndex, editedName, editedID, editedAge, editedIntake);
            }else{
                ProjManager.editStuAcc_sameIntake(stuIndex, editedName, editedID, editedAge, editedIntake);
            }

            //Return back to the student list page
            this.setVisible(false);
            backMainFrame();
        }
        catch(NumberFormatException numExc){
            JOptionPane.showMessageDialog(null,"You only can enter digit for age.","Invalid Age Input",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btbSubmitActionPerformed

    private void btbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelActionPerformed
        //Return back to the student list page
        this.setVisible(false);
        backMainFrame();
    }//GEN-LAST:event_btbCancelActionPerformed

    public void backMainFrame(){
        ProjManager_MainFrame fr = new ProjManager_MainFrame();
        fr.setVisible(true);

        fr.DashboardPane.setBackground(new Color(122, 162, 227));
        fr.AccManagementPane.setBackground(new Color(106, 212, 221));
        fr.PanelTitle.setText("Account Management");
        
        fr.createStuAccMgmtPane(fr, SelectedIntake);
        int tabIndex = fr.TabPanel.getTabCount();
        fr.changedTab(tabIndex-1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccMgmtFrame_EditStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccMgmtFrame_EditStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccMgmtFrame_EditStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccMgmtFrame_EditStu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFStuAge;
    private javax.swing.JTextField TFStuID;
    private javax.swing.JTextField TFStuName;
    private javax.swing.JButton btbCancel;
    private javax.swing.JButton btbSubmit;
    private javax.swing.JComboBox<String> cboStuIntake;
    private javax.swing.JLabel iconTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLectID1;
    private javax.swing.JLabel lblStuAge;
    private javax.swing.JLabel lblStuID;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
