package ProjManagerPackage;

import ProjManagerPackage.AssignSupvElem.TableHeader_StuAdvsList;
import ProjManagerPackage.StuAssessElem.ModernScrollBarUI;
import ProjManagerPackage.StuAssessElem.TableActionCellEditor;
import ProjManagerPackage.StuAssessElem.TableActionCellRender;
import ProjManagerPackage.StuAssessElem.TableActionEvent;
import StuPackage.StuData_IO;
import StuPackage.Student;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class AssignAdvsTab_StuAdvsList extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private String SelectedIntake;
    
    public AssignAdvsTab_StuAdvsList(MainFrame mainFrame, String selectedIntake, String selectedAsses) {
        this.mainFrame = mainFrame;
        SelectedIntake = selectedIntake;
        initComponents();
        
        //Customize Table Modification
        /* Set the scrollbar to customize scrollbar*/
        fixTable(jScrollPane1);
        
        /* Set the header to customize header */
        StuAdvsTable.getTableHeader().setReorderingAllowed(false);
        StuAdvsTable.getTableHeader().setResizingAllowed(false);
        StuAdvsTable.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object o, boolean isSelected, boolean hasFocus, int row, int column) {
                TableHeader_StuAdvsList header = new TableHeader_StuAdvsList(o + "");
                return header;
            }
        });

        //Edit the tab title and assessment
        TabTitle.setText(selectedIntake);
        selectedAssessment.setText(selectedAsses);
        
        //Insert data into table
        for (Student stu :StuData_IO.StuData){
            if (stu.intake.equals(selectedIntake)) {
            String StuName = stu.name;
            String StuID = stu.id;
            String Supervisor = stu.supervisor;
            String SecondMkr = stu.secondMarker;
            String RMCP_Lect = stu.RMCP_lecture;
            
            Object[] InsertRow = {StuName, StuID, Supervisor, SecondMkr, RMCP_Lect};

            DefaultTableModel model = (DefaultTableModel) StuAdvsTable.getModel();
            model.addRow(InsertRow);
            }
        }
        
        /*Set the edit button and its function*/
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                //Get the student id of selected student
                String selectedLectID = (String) StuAdvsTable.getValueAt(row, 1);
                mainFrame.dispose();
                
                AssignAdvsFrame_ToStu editPage = new AssignAdvsFrame_ToStu(selectedLectID);
                editPage.setVisible(true);
            }
        };
        
        //Insert edit button into table
        StuAdvsTable.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender());
        StuAdvsTable.getColumnModel().getColumn(5).setCellEditor(new TableActionCellEditor(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StuAdvsTable = new javax.swing.JTable();
        btbBack = new javax.swing.JLabel();
        TabTitle = new javax.swing.JLabel();
        lblAssessment = new javax.swing.JLabel();
        selectedAssessment = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StuAdvsTable.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        StuAdvsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Student ID", "Supervisor", "Second Marker", "RMCP Lecturer", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StuAdvsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StuAdvsTable.setRowHeight(40);
        jScrollPane1.setViewportView(StuAdvsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 886, 440));

        btbBack.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        btbBack.setForeground(new java.awt.Color(0, 0, 0));
        btbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/leftArrow(Black).png"))); // NOI18N
        btbBack.setText("Back...");
        btbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbBackMouseClicked(evt);
            }
        });
        add(btbBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        TabTitle.setFont(new java.awt.Font("Dubai Medium", 0, 28)); // NOI18N
        TabTitle.setForeground(new java.awt.Color(0, 0, 0));
        TabTitle.setText("APU2F2109");
        add(TabTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblAssessment.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblAssessment.setForeground(new java.awt.Color(0, 0, 0));
        lblAssessment.setText("Assessment:");
        add(lblAssessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        selectedAssessment.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        selectedAssessment.setForeground(new java.awt.Color(0, 0, 0));
        selectedAssessment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectedAssessment.setText("Investigation Report");
        add(selectedAssessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbBackMouseClicked
        mainFrame.createIntakeAdvsAllotPane(mainFrame, SelectedIntake);
        int tabIndex = mainFrame.TabPanel.getTabCount()-1;
        mainFrame.changedTab(tabIndex);
    }//GEN-LAST:event_btbBackMouseClicked

    /* Customize the scrollbar for table */
    public void fixTable (JScrollPane scroll){
        scroll.getViewport().setBackground(Color.WHITE);
        
        JScrollBar verticalScrollBar = scroll.getVerticalScrollBar();
        verticalScrollBar.setUI(new ModernScrollBarUI());

        // Set other properties of the vertical scroll bar
        verticalScrollBar.setPreferredSize(new Dimension(3, 5));
        verticalScrollBar.setForeground(new Color(71, 105, 231, 178));
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setOpaque(false);
        
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        scroll.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StuAdvsTable;
    private javax.swing.JLabel TabTitle;
    private javax.swing.JLabel btbBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessment;
    private javax.swing.JLabel selectedAssessment;
    // End of variables declaration//GEN-END:variables
}
