/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjManagerPackage;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class AssignAdvsFrame_LectRole extends javax.swing.JFrame {

    /**
     * Creates new form EditLectRoleFrame
     */
    public AssignAdvsFrame_LectRole(String selectedLectID) {
        
        //GUI Setting
        initComponents();
        getContentPane().setBackground(new Color(151, 231, 225));
        
        //Search the selected lecturer data
        lblSelectedName.setText("Alan");
        lblSelectedID.setText(selectedLectID);
        
        //Select the lecturer whether is supervisor and second marker
        RBSupervisor_Yes.setSelected(true);
        RBSecondMarker_No.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isSupervisorBG = new javax.swing.ButtonGroup();
        isSecondMarkerBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblSelectedName = new javax.swing.JLabel();
        lblLectName = new javax.swing.JLabel();
        lblSelectedID = new javax.swing.JLabel();
        lblSecondMarker = new javax.swing.JLabel();
        lblLectID = new javax.swing.JLabel();
        lblSupervisor = new javax.swing.JLabel();
        RBSupervisor_Yes = new javax.swing.JRadioButton();
        RBSupervisor_No = new javax.swing.JRadioButton();
        RBSecondMarker_Yes = new javax.swing.JRadioButton();
        RBSecondMarker_No = new javax.swing.JRadioButton();
        btbSubmit3 = new javax.swing.JButton();
        btbCancel = new javax.swing.JButton();
        lblTitle2 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        iconTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblSelectedName.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblSelectedName.setForeground(new java.awt.Color(0, 0, 0));
        lblSelectedName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSelectedName.setText("Shahab");

        lblLectName.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblLectName.setForeground(new java.awt.Color(0, 0, 0));
        lblLectName.setText("Lecturer Name:");

        lblSelectedID.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblSelectedID.setForeground(new java.awt.Color(0, 0, 0));
        lblSelectedID.setText("111222");

        lblSecondMarker.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblSecondMarker.setForeground(new java.awt.Color(0, 0, 0));
        lblSecondMarker.setText("Second Marker:");

        lblLectID.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblLectID.setForeground(new java.awt.Color(0, 0, 0));
        lblLectID.setText("Lecturer ID:");

        lblSupervisor.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblSupervisor.setForeground(new java.awt.Color(0, 0, 0));
        lblSupervisor.setText("Supervisor:");

        isSupervisorBG.add(RBSupervisor_Yes);
        RBSupervisor_Yes.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        RBSupervisor_Yes.setForeground(new java.awt.Color(0, 0, 0));
        RBSupervisor_Yes.setText("Yes");

        isSupervisorBG.add(RBSupervisor_No);
        RBSupervisor_No.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        RBSupervisor_No.setForeground(new java.awt.Color(0, 0, 0));
        RBSupervisor_No.setText("No");

        isSecondMarkerBG.add(RBSecondMarker_Yes);
        RBSecondMarker_Yes.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        RBSecondMarker_Yes.setForeground(new java.awt.Color(0, 0, 0));
        RBSecondMarker_Yes.setText("Yes");

        isSecondMarkerBG.add(RBSecondMarker_No);
        RBSecondMarker_No.setFont(new java.awt.Font("Dubai Medium", 0, 16)); // NOI18N
        RBSecondMarker_No.setForeground(new java.awt.Color(0, 0, 0));
        RBSecondMarker_No.setText("No");

        btbSubmit3.setBackground(new java.awt.Color(106, 212, 221));
        btbSubmit3.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        btbSubmit3.setForeground(new java.awt.Color(255, 255, 255));
        btbSubmit3.setText("Submit");
        btbSubmit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSubmit3ActionPerformed(evt);
            }
        });

        btbCancel.setBackground(new java.awt.Color(106, 212, 221));
        btbCancel.setFont(new java.awt.Font("Dubai Medium", 1, 15)); // NOI18N
        btbCancel.setForeground(new java.awt.Color(255, 255, 255));
        btbCancel.setText("Cancel");
        btbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btbSubmit3)
                    .addComponent(lblSupervisor)
                    .addComponent(lblSecondMarker)
                    .addComponent(lblLectName)
                    .addComponent(lblLectID))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectedID)
                            .addComponent(lblSelectedName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RBSecondMarker_Yes)
                                .addGap(30, 30, 30)
                                .addComponent(RBSecondMarker_No))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RBSupervisor_Yes)
                                .addGap(30, 30, 30)
                                .addComponent(RBSupervisor_No))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btbCancel)))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectedName)
                    .addComponent(lblLectName))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectedID)
                    .addComponent(lblLectID))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupervisor)
                    .addComponent(RBSupervisor_Yes)
                    .addComponent(RBSupervisor_No))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecondMarker)
                    .addComponent(RBSecondMarker_Yes)
                    .addComponent(RBSecondMarker_No))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbCancel)
                    .addComponent(btbSubmit3))
                .addGap(55, 55, 55))
        );

        lblTitle2.setFont(new java.awt.Font("Dubai Medium", 1, 38)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("Role");

        lblTitle1.setFont(new java.awt.Font("Dubai Medium", 1, 38)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("Edit Lecturer");

        iconTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LectureRole.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblTitle2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(iconTitle)))
                .addGap(75, 75, 75)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconTitle)
                .addGap(0, 0, 0)
                .addComponent(lblTitle1)
                .addGap(0, 0, 0)
                .addComponent(lblTitle2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbSubmit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSubmit3ActionPerformed
        
    }//GEN-LAST:event_btbSubmit3ActionPerformed

    private void btbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelActionPerformed
        //Return back to the student list page
        this.setVisible(false);
        backMainFrame();
    }//GEN-LAST:event_btbCancelActionPerformed

    public void backMainFrame(){
        MainFrame fr = new MainFrame();
        fr.setVisible(true);

        fr.DashboardPane.setBackground(new Color(122, 162, 227));
        fr.AssignAdvisorsPane.setBackground(new Color(106, 212, 221));
        fr.PanelTitle.setText("Assign Advisors");
        fr.changedTab(4);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignAdvsFrame_LectRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignAdvsFrame_LectRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignAdvsFrame_LectRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignAdvsFrame_LectRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBSecondMarker_No;
    private javax.swing.JRadioButton RBSecondMarker_Yes;
    private javax.swing.JRadioButton RBSupervisor_No;
    private javax.swing.JRadioButton RBSupervisor_Yes;
    private javax.swing.JButton btbCancel;
    private javax.swing.JButton btbSubmit3;
    private javax.swing.JLabel iconTitle;
    private javax.swing.ButtonGroup isSecondMarkerBG;
    private javax.swing.ButtonGroup isSupervisorBG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLectID;
    private javax.swing.JLabel lblLectName;
    private javax.swing.JLabel lblSecondMarker;
    private javax.swing.JLabel lblSelectedID;
    private javax.swing.JLabel lblSelectedName;
    private javax.swing.JLabel lblSupervisor;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
