/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProjManagerPackage;

import ProjManagerPackage.DashboardElem.TableActionCellRender_DashMark;
import ProjManagerPackage.DashboardElem.TableActionCellRender_DashPending;
import ProjManagerPackage.DashboardElem.TableHeader_Dashboard;
import ProjManagerPackage.StuAssessElem.ModernScrollBarUI;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class Dashboard extends javax.swing.JPanel {

    private MainFrame mainFrame;
    
    public Dashboard(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        
        //Customize Table Modification
        /* Set the scrollbar to customize scrollbar*/
        fixTable(jScrollPane1);
        
        /* Set the header to customize header */
        StuRptStatusTable.getTableHeader().setReorderingAllowed(false);
        StuRptStatusTable.getTableHeader().setResizingAllowed(false);
        StuRptStatusTable.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object o, boolean isSelected, boolean hasFocus, int row, int column) {
                TableHeader_Dashboard header = new TableHeader_Dashboard(o + "");
                return header;
            }
        });

        
        //Insert data into table
        /*Show the student haven't been alloted assesment*/
//        for (Student stu :StuData_IO.StuData){
//            String StuName = stu.name;
//            String StuID = stu.id;
//            String Intake = stu.intake;
//            String Assessment = stu.assessment;
//            
//            if (Assessment.equals("-")) {
//            Object[] InsertRow = {StuName, StuID, Intake, Assessment};
//
//            DefaultTableModel model = (DefaultTableModel) LectRoleTable.getModel();
//            model.addRow(InsertRow);
//            }
//        }
        
        /*Show the student have been alloted assesment*/
        for (int count = 0; count < 3; count++){
            String StuName = "John";
            String StuID = "TP111222";
            String Intake = "APU2F2402";
            String Assessment = "CP2";
            String RptStatus = "Pending";


            Object[] InsertRow = {StuName, StuID, Intake, Assessment};

            DefaultTableModel model = (DefaultTableModel) StuRptStatusTable.getModel();
            model.addRow(InsertRow);
            
            if (RptStatus.equals("Mark")) {
                StuRptStatusTable.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender_DashMark());
            }
            else if(RptStatus.equals("Pending")){
                StuRptStatusTable.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender_DashPending());
            }
        }

            
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxRptStatus = new javax.swing.JPanel();
        btbSeeMore = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StuRptStatusTable = new javax.swing.JTable();
        TabTitle = new javax.swing.JLabel();
        boxTtlLect = new javax.swing.JPanel();
        lblNumLect = new javax.swing.JLabel();
        lblTtlLect = new javax.swing.JLabel();
        LectIcon = new javax.swing.JLabel();
        boxTtlIntake = new javax.swing.JPanel();
        IntakeIcon = new javax.swing.JLabel();
        lblTtlIntake = new javax.swing.JLabel();
        lblNumIntake = new javax.swing.JLabel();
        boxTtlStu = new javax.swing.JPanel();
        lblTtlStu = new javax.swing.JLabel();
        lblNumStu = new javax.swing.JLabel();
        StuIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxRptStatus.setBackground(new java.awt.Color(255, 255, 255));
        boxRptStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btbSeeMore.setFont(new java.awt.Font("Dubai Medium", 0, 15)); // NOI18N
        btbSeeMore.setForeground(new java.awt.Color(0, 0, 0));
        btbSeeMore.setText("See More...");
        btbSeeMore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbSeeMoreMouseClicked(evt);
            }
        });
        boxRptStatus.add(btbSeeMore, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 70, 30));

        StuRptStatusTable.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        StuRptStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Student ID", "Intake", "Assessment", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StuRptStatusTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StuRptStatusTable.setRowHeight(40);
        jScrollPane1.setViewportView(StuRptStatusTable);

        boxRptStatus.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 840, 290));

        TabTitle.setFont(new java.awt.Font("Dubai Medium", 0, 23)); // NOI18N
        TabTitle.setForeground(new java.awt.Color(0, 0, 0));
        TabTitle.setText("Report Status");
        boxRptStatus.add(TabTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        add(boxRptStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 880, 350));

        boxTtlLect.setBackground(new java.awt.Color(137, 225, 96));
        boxTtlLect.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumLect.setFont(new java.awt.Font("Dubai Medium", 1, 30)); // NOI18N
        lblNumLect.setForeground(new java.awt.Color(255, 255, 255));
        lblNumLect.setText("20");
        boxTtlLect.add(lblNumLect, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblTtlLect.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lblTtlLect.setForeground(new java.awt.Color(255, 255, 255));
        lblTtlLect.setText("Total Lecturer");
        boxTtlLect.add(lblTtlLect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        LectIcon.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        LectIcon.setForeground(new java.awt.Color(255, 255, 255));
        LectIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dashboard_Lect.png"))); // NOI18N
        boxTtlLect.add(LectIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        add(boxTtlLect, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 270, 130));

        boxTtlIntake.setBackground(new java.awt.Color(200, 88, 239));
        boxTtlIntake.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IntakeIcon.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        IntakeIcon.setForeground(new java.awt.Color(255, 255, 255));
        IntakeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Darshboard_Intake.png"))); // NOI18N
        boxTtlIntake.add(IntakeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblTtlIntake.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lblTtlIntake.setForeground(new java.awt.Color(255, 255, 255));
        lblTtlIntake.setText("Total Intake");
        boxTtlIntake.add(lblTtlIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblNumIntake.setFont(new java.awt.Font("Dubai Medium", 1, 30)); // NOI18N
        lblNumIntake.setForeground(new java.awt.Color(255, 255, 255));
        lblNumIntake.setText("4");
        boxTtlIntake.add(lblNumIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        add(boxTtlIntake, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 130));

        boxTtlStu.setBackground(new java.awt.Color(234, 175, 86));
        boxTtlStu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTtlStu.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        lblTtlStu.setForeground(new java.awt.Color(255, 255, 255));
        lblTtlStu.setText("Total Student");
        boxTtlStu.add(lblTtlStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblNumStu.setFont(new java.awt.Font("Dubai Medium", 1, 30)); // NOI18N
        lblNumStu.setForeground(new java.awt.Color(255, 255, 255));
        lblNumStu.setText("30");
        boxTtlStu.add(lblNumStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        StuIcon.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        StuIcon.setForeground(new java.awt.Color(255, 255, 255));
        StuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dashboard_Stu.png"))); // NOI18N
        boxTtlStu.add(StuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        add(boxTtlStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 270, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btbSeeMoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbSeeMoreMouseClicked
        mainFrame.DashboardPane.setBackground(new Color(122, 162, 227));
        mainFrame.ReportStatusPane.setBackground(new Color(106, 212, 221));
        mainFrame.PanelTitle.setText("Report Status");
        mainFrame.changedTab(11);
    }//GEN-LAST:event_btbSeeMoreMouseClicked

    /* Customize the scrollbar for table */
    public void fixTable (JScrollPane scroll){
        scroll.getViewport().setBackground(Color.WHITE);
        
        JScrollBar verticalScrollBar = scroll.getVerticalScrollBar();
        verticalScrollBar.setUI(new ModernScrollBarUI());

        // Set other properties of the vertical scroll bar
        verticalScrollBar.setPreferredSize(new Dimension(3, 5));
        verticalScrollBar.setForeground(new Color(71, 105, 231, 178));
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setOpaque(false);
        
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        scroll.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IntakeIcon;
    private javax.swing.JLabel LectIcon;
    private javax.swing.JLabel StuIcon;
    private javax.swing.JTable StuRptStatusTable;
    private javax.swing.JLabel TabTitle;
    private javax.swing.JPanel boxRptStatus;
    private javax.swing.JPanel boxTtlIntake;
    private javax.swing.JPanel boxTtlLect;
    private javax.swing.JPanel boxTtlStu;
    private javax.swing.JLabel btbSeeMore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumIntake;
    private javax.swing.JLabel lblNumLect;
    private javax.swing.JLabel lblNumStu;
    private javax.swing.JLabel lblTtlIntake;
    private javax.swing.JLabel lblTtlLect;
    private javax.swing.JLabel lblTtlStu;
    // End of variables declaration//GEN-END:variables
}
