package ProjManagerPackage;

import ProjManagerPackage.StuAsseTabElement.IntakeBasedMethod;
import StuPackage.StuData_IO;
import StuPackage.Student;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class EditAssFrame_StuBased extends javax.swing.JFrame {

    private String stuID;
    private String currentAssessment;

    /**
     * Creates new form EditAssessmentFrame
     */
    public EditAssFrame_StuBased(String StuID) {
        //Pass the Student ID to class object(stuID)
        stuID = StuID;

        //GUI setting
        initComponents();
        getContentPane().setBackground(new Color(204, 204, 255));

        //Search the selected student data
        for (int i = 0; i < StuData_IO.StuData.size(); i++) {
            if (StuData_IO.StuData.get(i).id.equals(StuID)) {
                lblSelectedName.setText(StuData_IO.StuData.get(i).name);
                lblSelectedID.setText(StuData_IO.StuData.get(i).id);
                lblSelectedIntake.setText(StuData_IO.StuData.get(i).intake);
                currentAssessment = StuData_IO.StuData.get(i).assessment;
                break;
            }
        }
        
        cboAssesment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"-", "Intern", "Investigation Report", "CP1", "CP2", "RMCP", "FYP"}));
        cboAssesment.setSelectedItem(currentAssessment);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblStuName = new javax.swing.JLabel();
        lblSelectedName = new javax.swing.JLabel();
        lblStuID = new javax.swing.JLabel();
        lblSelectedID = new javax.swing.JLabel();
        lblIntake = new javax.swing.JLabel();
        lblSelectedIntake = new javax.swing.JLabel();
        lbAssesment = new javax.swing.JLabel();
        cboAssesment = new javax.swing.JComboBox<>();
        btbSubmit = new javax.swing.JButton();
        btbCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Dubai Medium", 1, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(115, 96, 223));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitle.setText("Student Assessment");

        lblStuName.setFont(new java.awt.Font("Dubai Medium", 1, 22)); // NOI18N
        lblStuName.setForeground(new java.awt.Color(115, 96, 223));
        lblStuName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStuName.setText("Student Name: ");

        lblSelectedName.setFont(new java.awt.Font("Dubai Medium", 1, 22)); // NOI18N
        lblSelectedName.setForeground(new java.awt.Color(115, 96, 223));
        lblSelectedName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSelectedName.setText(" ");

        lblStuID.setFont(new java.awt.Font("Dubai Medium", 1, 22)); // NOI18N
        lblStuID.setForeground(new java.awt.Color(115, 96, 223));
        lblStuID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStuID.setText("Student ID: ");

        lblSelectedID.setFont(new java.awt.Font("Dubai Medium", 1, 22)); // NOI18N
        lblSelectedID.setForeground(new java.awt.Color(115, 96, 223));
        lblSelectedID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSelectedID.setText(" ");

        lblIntake.setFont(new java.awt.Font("Dubai Medium", 1, 22)); // NOI18N
        lblIntake.setForeground(new java.awt.Color(115, 96, 223));
        lblIntake.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIntake.setText("Intake: ");

        lblSelectedIntake.setFont(new java.awt.Font("Dubai Medium", 1, 22)); // NOI18N
        lblSelectedIntake.setForeground(new java.awt.Color(115, 96, 223));
        lblSelectedIntake.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSelectedIntake.setText(" ");

        lbAssesment.setFont(new java.awt.Font("Dubai Medium", 1, 22)); // NOI18N
        lbAssesment.setForeground(new java.awt.Color(115, 96, 223));
        lbAssesment.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAssesment.setText("Assessment: ");

        cboAssesment.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        cboAssesment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btbSubmit.setBackground(new java.awt.Color(115, 96, 223));
        btbSubmit.setFont(new java.awt.Font("Dubai Medium", 1, 16)); // NOI18N
        btbSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btbSubmit.setText("Submit");
        btbSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbSubmitActionPerformed(evt);
            }
        });

        btbCancel.setBackground(new java.awt.Color(115, 96, 223));
        btbCancel.setFont(new java.awt.Font("Dubai Medium", 1, 15)); // NOI18N
        btbCancel.setForeground(new java.awt.Color(255, 255, 255));
        btbCancel.setText("Cancel");
        btbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStuID)
                    .addComponent(lblStuName)
                    .addComponent(lbAssesment)
                    .addComponent(lblIntake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelectedName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectedID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectedIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAssesment, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btbSubmit)
                        .addGap(113, 113, 113)
                        .addComponent(btbCancel))
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSelectedName)
                    .addComponent(lblStuName))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSelectedID)
                    .addComponent(lblStuID))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntake)
                    .addComponent(lblSelectedIntake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAssesment)
                    .addComponent(cboAssesment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbCancel)
                    .addComponent(btbSubmit))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCancelActionPerformed
        //Return back to the student list page
        this.setVisible(false);
        backMainFrame();
    }//GEN-LAST:event_btbCancelActionPerformed

    private void btbSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbSubmitActionPerformed
        //Search the selected student location and
        int stuIndex = StuData_IO.checkStu(stuID);

        //Get all the selected student data
        String Name = StuData_IO.StuData.get(stuIndex).name;
        int Age = StuData_IO.StuData.get(stuIndex).age;
        String Intake = StuData_IO.StuData.get(stuIndex).intake;
        String Assessment = (String) cboAssesment.getSelectedItem();
        String Supervisor = StuData_IO.StuData.get(stuIndex).supervisor;
        String SecondMaker = StuData_IO.StuData.get(stuIndex).secondMaker;

        //Make sure the selected assessment is comfort with his intake (if his intake is alloted assessment already)
        boolean assChecking = IntakeBasedMethod.checkAssessment(Intake, Assessment);
        
        if (assChecking == true) {
             //Update the edited data into ArrayList
            Student Edited_Student = new Student(Name, Age, stuID, Intake, Assessment, Supervisor, SecondMaker);
            StuData_IO.edit(stuIndex, Edited_Student);

            //Return back to the student list page
            this.setVisible(false);
            backMainFrame();
        }
        else{
            String actualAss = IntakeBasedMethod.getAssessment(Intake);
            JOptionPane.showMessageDialog(null,"This intake is alloted with " + actualAss + " assessment."
                    + "\nYou only can choose " + actualAss + " for the assessment."
                    ,"Incorrect Assessment Selection",JOptionPane.WARNING_MESSAGE);
            cboAssesment.setSelectedItem(Assessment);
        }
    }//GEN-LAST:event_btbSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void backMainFrame(){
        ProjMng_MainFrame fr = new ProjMng_MainFrame();
        fr.setVisible(true);
        
        fr.ManageAssessmentPane.setBackground(new Color(122, 162, 227));
        fr.StuAssessmentPane.setBackground(new Color(106, 212, 221));
        fr.PanelTitle.setText("Student Assessment");
        fr.changedTab(2);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAssFrame_StuBased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAssFrame_StuBased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAssFrame_StuBased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAssFrame_StuBased.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCancel;
    private javax.swing.JButton btbSubmit;
    private javax.swing.JComboBox<String> cboAssesment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAssesment;
    private javax.swing.JLabel lblIntake;
    private javax.swing.JLabel lblSelectedID;
    private javax.swing.JLabel lblSelectedIntake;
    private javax.swing.JLabel lblSelectedName;
    private javax.swing.JLabel lblStuID;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
