package ProjManagerPackage;

import ProjManagerPackage.RptStatusElem.TableActionCellRender_RptStatusIcon;
import ProjManagerPackage.RptStatusElem.TableHeader_StuList;
import ProjManagerPackage.StuAssesElem.IntakeBasedMethod;
import ProjManagerPackage.StuAssesElem.ModernScrollBarUI;
import StuPackage.StuData_IO;
import StuPackage.Student;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class RptStatus_StuList extends javax.swing.JPanel {

    private MainFrame mainFrame;
    
    public RptStatus_StuList(MainFrame mainFrame, String selectedIntake) {
        this.mainFrame = mainFrame;
        initComponents();
        
        //Customize Table Modification
        /* Set the scrollbar to customize scrollbar*/
        fixTable(jScrollPane1);
        
        /* Set the header to customize header */
        StuRptStatusTable.getTableHeader().setReorderingAllowed(false);
        StuRptStatusTable.getTableHeader().setResizingAllowed(false);
        StuRptStatusTable.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object o, boolean isSelected, boolean hasFocus, int row, int column) {
                TableHeader_StuList header = new TableHeader_StuList(o + "");
                return header;
            }
        });

        
        //Insert data into table
        TabTitle.setText(selectedIntake);
        selectedAssessment.setText(IntakeBasedMethod.getAssessment(selectedIntake));
        
        /*Retrieve student data*/
        for (Student stu :StuData_IO.StuData){
            if (stu.intake.equals(selectedIntake)) {
                String StuName = stu.name;
                String StuID = stu.id;
                String Supervisor = stu.supervisor;
                String SecondMkr = stu.secondMarker;
                String RMCP_Lect = stu.RMCP_lecture;


                Object[] InsertRow = {StuName, StuID, Supervisor, SecondMkr, RMCP_Lect};

                DefaultTableModel model = (DefaultTableModel) StuRptStatusTable.getModel();
                model.addRow(InsertRow);
                
                //Get the report status
                try{
                    System.out.println("test");
                    Scanner scan = new Scanner(new File("ReportData.txt"));

                    while(scan.hasNext()){
                        String currentLine = scan.nextLine();
                        String[] StuData_Array = currentLine.split(",");

                        if (StuData_Array[0].trim().equals(StuID)) {
                            String SubmitStatus = StuData_Array[2];
                            String GradeStatus = StuData_Array[3];
                            
                            System.out.println(SubmitStatus);
                            System.out.println(GradeStatus);
                            
                            StuRptStatusTable.getColumnModel().getColumn(5).setCellRenderer(new TableActionCellRender_RptStatusIcon());
                            
                            if (SubmitStatus.equals("No Attempt")) {
                                model.setValueAt(TableActionCellRender_RptStatusIcon.STATUS_NOSUBMITTED, model.getRowCount() - 1, 5);
                            }else{
                                if (GradeStatus.equals("Not Graded")) {
                                    model.setValueAt(TableActionCellRender_RptStatusIcon.STATUS_PENDING, model.getRowCount() - 1, 5);
                                }else{
                                    model.setValueAt(TableActionCellRender_RptStatusIcon.STATUS_MARKED, model.getRowCount() - 1, 5);
                                }
                            }
                        }
                    }
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"!Read student report status error!");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StuRptStatusTable = new javax.swing.JTable();
        TabTitle = new javax.swing.JLabel();
        lblAssessment = new javax.swing.JLabel();
        selectedAssessment = new javax.swing.JLabel();
        btbBack = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StuRptStatusTable.setBackground(new java.awt.Color(236, 236, 236));
        StuRptStatusTable.setFont(new java.awt.Font("Dubai Medium", 0, 17)); // NOI18N
        StuRptStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Student ID", "Supervisor", "Second Marker", "RMCP Lecturer", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StuRptStatusTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        StuRptStatusTable.setRowHeight(40);
        jScrollPane1.setViewportView(StuRptStatusTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 886, 440));

        TabTitle.setFont(new java.awt.Font("Dubai Medium", 0, 28)); // NOI18N
        TabTitle.setForeground(new java.awt.Color(0, 0, 0));
        TabTitle.setText("APU2F2109");
        add(TabTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        lblAssessment.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        lblAssessment.setForeground(new java.awt.Color(0, 0, 0));
        lblAssessment.setText("Assessment:");
        add(lblAssessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        selectedAssessment.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        selectedAssessment.setForeground(new java.awt.Color(0, 0, 0));
        selectedAssessment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        selectedAssessment.setText("Investigation Report");
        add(selectedAssessment, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, -1));

        btbBack.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        btbBack.setForeground(new java.awt.Color(0, 0, 0));
        btbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/leftArrow(Black).png"))); // NOI18N
        btbBack.setText("Back...");
        btbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbBackMouseClicked(evt);
            }
        });
        add(btbBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbBackMouseClicked
        mainFrame.changedTab(8);
    }//GEN-LAST:event_btbBackMouseClicked

    /* Customize the scrollbar for table */
    public void fixTable (JScrollPane scroll){
        scroll.getViewport().setBackground(Color.WHITE);
        
        JScrollBar verticalScrollBar = scroll.getVerticalScrollBar();
        verticalScrollBar.setUI(new ModernScrollBarUI());

        // Set other properties of the vertical scroll bar
        verticalScrollBar.setPreferredSize(new Dimension(3, 5));
        verticalScrollBar.setForeground(new Color(71, 105, 231, 178));
        verticalScrollBar.setUnitIncrement(20);
        verticalScrollBar.setOpaque(false);
        
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        scroll.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StuRptStatusTable;
    private javax.swing.JLabel TabTitle;
    private javax.swing.JLabel btbBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessment;
    private javax.swing.JLabel selectedAssessment;
    // End of variables declaration//GEN-END:variables
}
